#!/usr/bin/env bash

##Update the package index
sudo apt-get update

## Install Nginx
sudo apt-get install nginx -y

## Configure Nginx
echo "server {
        listen 80 default_server;
        root /var/www/html;
        index index.html;
        server_name _;
        location / {
                # Return Hello World! as the response
                echo 'Hello World!';
        }
}" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx
sudo /etc/init.d/nginx restart
